# Generated by Django 4.1.5 on 2023-01-28 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_galary'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Image',
        ),
        migrations.AddField(
            model_name='galary',
            name='description',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='galary',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
