# Generated by Django 4.1.5 on 2023-01-29 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_delete_image_galary_description_galary_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='galary',
            name='iid',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
